debug: true

proxy:
  coll: coll
  recording: true

  enable_banner: false
  enable_wombat: true

recorder: live

autoindex: 10

enable_auto_fetch: true

collections:
  live: $live

collections_root: /webarchive/collections
  
